title: Ommadawn.es
description: Long Form Jekyll theme built with SASS

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Blog
      url: /index.html
    - title: Discografia
      url: /discografia
#    - title: Conciertos
#      url: /conciertos

#social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com
#    linkedin: brianmaierjr
#    youtube: RickAstleyYT
#    tumblr: i-am-a-fish

google_analytics: "G-VW0D18SS0Y"

disqus:
    shortname: brianmaierjr
